### ISSUE TITLE
How long to wait for the CorsacHats mod for the new version of the game?

### ISSUE THREAD

**Issue by woky77** [kiraacorsac/CorsacHats#5]
Hi. Now a new update has been released in the game Among Us. So, I would like to ask, how long to wait for the CorsacHats mod for the new version of the game?

**Comment by amsryq** [comment]
#6 [CorsacHats.dll](https://github.com/amsyarasyiq/CorsacHats//blob/master/build/CorsacHats.dll)

**Comment by kiraacorsac** [comment]
You can stop waiting now :) Thanks, @amsyarasyiq!
